### ISSUE TITLE
remove requirement for composer path configuration

### ISSUE THREAD

**Issue by glensc** [felipebool/crook#3]
instead of this commit: https://github.com/felipebool/crook/commit/f0be111c9bb42a889a0965c457c2b4e1b0397f6c

The project should fall back to `composer` or `composer.phar` from `PATH`.

Its unnecessary extra step to use the project. besides having this configurable via `crook.json` makes it impossible to share `crook.json` with other developers, i.e commit the file to git repo.

**Comment by felipebool** [comment]
Hmmm, interesting insights, I'm gonna take a look at this.

**Comment by glensc** [comment]
this is a blocker for me to use this project. looking for alternatives.
