### ISSUE TITLE
move `theHook` to `.git/hooks/crook.php`

### ISSUE THREAD

**Issue by glensc** [felipebool/crook#5]
rationale: do not trash project root, project owners need to add `theHook` to `.gitignore`, which is just annoying.

**Comment by felipebool** [comment]
Thanks, @glensc. I'm gonna do some changes in the next days and this one will probably be added.
Btw, how is the experience with crook so far?

**Comment by glensc** [comment]
@felipebool thanks. I found more suitable solution for me: https://github.com/BrainMaestro/composer-git-hooks
